name = "Toshi's Minecraft Server"
author = "Toshi2D"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c63f5e1ed1e3c3f74d7f3d209b0e90ee8d102570391d7e229c34d4cbd4e094ec"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
