name = "Toshi's Minecraft Server"
author = "toshi2d"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc6d1b1856e582fa56fc818d2ecbfd222d489e4ec574675a932ac3d8196ecad2"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
