name = "Toshi's Minecraft Server"
author = "Toshi2D"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "194d3430885a8f136e9b9e3a1bba00f8cdeffb48abe704141c1cb2cf7d46b320"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
